filter:
  dependency_paths:
    - "vendor/"
  excluded_paths:
    - 'test/'

build:
  environment:
    php:
      version: '7.4'

  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

    coverage:
      tests:
        override:
          - command: './bin/phing unit'
            coverage:
              file:   'test/coverage.xml'
              format: 'php-clover'
